[package]
name = "test_sst_importer"
version = "0.1.0"
edition = "2018"
publish = false
description = "test helpers for sst_importer"

[lib]
test = false

[dependencies]
crc32fast = "1.2"
engine_rocks = { path = "../engine_rocks", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
keys = { path = "../keys", default-features = false }
kvproto = { git = "https://github.com/coocood/kvproto.git", rev = "c182ab01a5ed95293ed430b955489e2e2c509ca8" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
