[package]
name = "error_code"
version = "0.0.1"
edition = "2018"
publish = false

[lib]
name = "error_code"
path = "src/lib.rs"

[[bin]]
name = "error_code_gen"
path = "bin.rs"

[dependencies]
lazy_static = "1.3"
raft = { version = "0.6.0-alpha", default-features = false, features = ["protobuf-codec"] }
kvproto = { git = "https://github.com/coocood/kvproto.git", rev = "128b6a780ee757fe66484bf324673abb4f868473" }
tikv_alloc = { path = "../tikv_alloc" }
grpcio = { version = "0.9",  default-features = false, features = ["openssl-vendored", "protobuf-codec"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
