[package]
name = "cloud"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1"
derive_more = "0.99.3"
error_code = { path = "../error_code", default-features = false }
futures-io = "0.3"
kvproto = { git = "https://github.com/coocood/kvproto.git", rev = "128b6a780ee757fe66484bf324673abb4f868473" }
openssl = "0.10"
protobuf = { version = "2.8", features = ["bytes"] }
rusoto_core = "0.46.0"
thiserror = "1.0"
tikv_util = { path = "../tikv_util", default-features = false }
url = "2.0"

[dev-dependencies]
fail = "0.5"
