[package]
name = "rfstore"
version = "0.0.1"
authors = ["The TiKV Authors"]
license = "Apache-2.0"
edition = "2018"
publish = false


[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "protobuf/bytes",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec",
]

[dependencies]
bitflags = "1.0.1"
bytes = "1.0"
byteorder = "1.2"
crossbeam = "0.8"
dashmap = "4.0"
encryption = { path = "../encryption", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
error_code = { path = "../error_code", default-features = false }
log_wrappers = { path = "../log_wrappers" }
protobuf = "2.8"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
raft-proto = { version = "0.6.0-alpha", default-features = false }
online_config = { path = "../online_config" }
fail = "0.4"
futures = "0.3"
futures-util = { version = "0.3.1", default-features = false, features = ["io"] }
crc32c = "0.6"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
slog-term = "2.4"
thiserror = "1.0"
kvenginepb = { path = "../kvenginepb", default-features = false }
kvengine = { path = "../kvengine"}
rfengine = { path = "../rfengine"}
tokio = { version = "1.5", features = ["full"] }
grpcio = { version = "0.9",  default-features = false}
pd_client = { path = "../pd_client", default-features = false }
tikv_util = { path = "../tikv_util", default-features = false }
time = "0.1"
