[package]
name = "into_other"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
kvproto = { git = "https://github.com/coocood/kvproto.git", rev = "c182ab01a5ed95293ed430b955489e2e2c509ca8" }
raft = { version = "0.6.0-alpha", default-features = false, features = ["protobuf-codec"] }
