[package]
name = "into_other"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
kvproto = { git = "https://github.com/coocood/kvproto.git", rev = "128b6a780ee757fe66484bf324673abb4f868473" }
raft = { version = "0.6.0-alpha", default-features = false, features = ["protobuf-codec"] }
