[package]
name = "kvengine"
version = "0.0.1"
authors = ["The TiKV Authors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
protobuf-codec = [
    "protobuf/bytes",
]

[dependencies]
async-trait = "0.1"
aws-config = "0.3.0"
aws-sdk-s3 = "0.3.0"
aws-types = "0.3.0"
bytes = "1.0"
thiserror = "1.0"
rand = "0.8"
byteorder = "1.2"
futures = { version = "0.3", features = ["thread-pool"] }
dashmap = "4.0"
dyn-clone = "1.0"
fslock = "0.1.7"
http = "0.2"
moka = "0.5.1"
farmhash = "1.1.5"
crc32c = "0.6"
kvenginepb = { path = "../kvenginepb", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
slog-term = "2.4"
protobuf = "2.8"
tokio = { version = "1.5", features = ["full"] }
tikv_util = { path = "../tikv_util", default-features = false}
engine_traits = { path = "../engine_traits", default-features = false }
txn_types = { path = "../txn_types", default-features = false }

[dev-dependencies]
tempfile = "3"