[package]
name = "test_cloud_server"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloud_server = { path = "../cloud_server" }
futures = "0.3"
grpcio = { version = "0.10", default-features = false, features = ["openssl-vendored", "protobuf-codec"] }
kvengine = { path = "../kvengine" }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
pd_client = { path = "../pd_client", default-features = false }
rand = "0.8"
rfengine = { path = "../rfengine" }
rfstore = { path = "../rfstore" }
security = { path = "../security", default-features = false }
tempfile = "3.0"
test_raftstore = { path = "../test_raftstore" }
test_util = { path = "../test_util" }
tikv = { path = "../.." }
tikv_util = { path = "../tikv_util" }
