name: CI

on:
  pull_request:
    branches:
      - cloud-engine
  workflow_dispatch:

# Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dev:
    name: Run clippy and rustfmt then build and test
    runs-on: large-quota
    env:
      RUSTFLAGS: -Dwarnings
      FAIL_POINT: "1"
      ROCKSDB_SYS_SSE: "1"
      RUST_BACKTRACE: "1"
      LOG_LEVEL: INFO
      EXTRA_CARGO_ARGS: --no-run
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: Install `rust` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-02-14
          default: true
          profile: minimal
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Cache cargo registry
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-
      - name: Run clippy
        working-directory: ./
        run: make clippy
      - name: Run build
        working-directory: ./
        run: make build
      - name: Run tests
        env:
          CARGO_INCREMENTAL: "0"
        working-directory: ./
        run: |
          cargo test -p rfstore -p rfengine -p kvengine --tests
          cargo test -p tests --test cloud_engine
